sudo: required

services:
  - docker

language: rust

cache: cargo

rust:
  - stable
  - nightly

env:
  global:
    # CRATES_IO_TOKEN
    - secure: HCIhhVrX0hLJtnPGHzIaw60y4XDu9ZF6nHsDVqhWTukzM/J8jDoufVP70mm/dhTpIkrMHhs05/x9BRNqwHObuTW82SlyENs9714r9nljVD/qwy6I2gRbUPXY9p5CTeNeRrzkcaZa4nZ7lQ1R4GqlviH1bJfYqT0tO0wq+3LMvTdY2VCptfwUZZpfkQFw2F2uK4gFMnnJOiCHizbttdv7ZlSi75ngS+q+G0g6QAgUA4Xe5uo9KvNLJpNpQ4aQulyn4UuHBX+Nfqq1tq+UdxaLdXZOB7VWK/3BYnl9kSuFQMQoZ4DIGgYnURL39wsXmawkT7YIuhoHN4o3M7Z0Ay0lcTEq03ev9oMyxz4v/oQKpCBVUdbKL15IQsOrDynK3vh6MEqWyoyQfpQy+VhFlrY7wOrrkOhFXOsv2+lJzfodXVvlfKAwLuvASnbFV9l+z3+JA0L1IKWgiJXeIhsz6eSkkU/vReeNVIvwBN8Dk9HDrkeKJvFGkPZDNEsQhnrJ6jRHXq0sMSA6Y2RPYcup3uLzjrgdjB6NZvDjjNWrm+1J8Na28NzCy/O95eyn3fE5HVgfCSdDmwG7H4yQIUBAlflXLvXSEaK/8JGFXhsyG8pZEwQd70HlLWglxaIFOdpymr8oskymxFfGIz/ULKi9gcvuZrrec7JW1c/YEe2g9fWWsG4=
    # DOCKER_USERNAME
    - secure: 4jkknU2lJ8YbXlO1nvLtHY1PNz8+qCVRpNVbrMD4TDIcD+5YKBhqdZOOPyEnZa3EaFU2bnK8dn52IOmZJ9Vmp7j4fqqW5Ls8prwqRr1FWVuI0SmDownM0CQJBVuoupli47R5fIKsqJmgirg2j+uXygC8kysbRU/9nKq4IyYM7B4DlKno7ANUImdqXuj43sokWpuJvRWwkwjfEEDhm0cuaClPtr9VoyNACZ2/jOGUiJz1tvxfaGepM9YyBKC7y/nx8jHxOhWBYuHbP/Y8yCf39UmmxmJu5GYvOvOK2BBSrQksJtL3tyapAJjIogUZJ/mL67ThlzPj7wLLX/GVqrupbk2834uWzuwigOeJOa9XMMv7fTqlXBT9JqzgChPSH5W6mgTWBsA1z6IRvqWCylNT9Fv7z85UqLy4yxcoZ3dVvdU+ocY6RrEGDCxZsQw8SMrjFoXY2GD8jw1M2skPZOouHigoqKnIBGK1cBjINJiY4wI1/vZxiRSgWI/cTmhNg2Q7KxQh5wiwU36xHsYWjuv6ChEd4Kro1kSqWNwMZnhwSK9RS49o8y7tX0+++Tt22F8dopN6MSLCi3d1pvBt8lsyOq5jtsRNwbI111MA3hloogIhqqofp9vSy1GNG0rGFD3GaimUItvWFAV3pxqU9k6RqEpMz4u+JYX8appaWeGo1ZU=
    # DOCKER_PASSWORD
    - secure: s2oNx4UzWHrj6vaUoBlcs5jGNCxAyZDGu4GDzauFU5oRH1TSWl77ln6sjHBo7demMYgVAVXsCHMCxB6vjukHy+wdS3Td3tzzovoDLRJPmv56EdNGO3cSpNJWxOXKePAML/OdQSzl/ozse9tbS3hH+dKq+mm8OqUmj1yhhNfFEVGze2p5R6n3PqJQ5ZwVTriD2M6GmrfPuRgbn++ArRnd0VP2JgQ7gq3YkCCzvdENyNNrMCiCqafKwcrsktn4kWoFL7MPOyWojQAma7b7zuJNOiafvukLJ1Z82ZWZ7vlCtIo8Evp0x3BMVzqfrSDKw1XcSIP/gejHiyd7isPLHtCANt4NfxGVTUvJCIL7LyxumNDolsLKmKnnBVeeg0gGNIULzOqFS0csLO5zAZL8rqfo/04bb6cXsN15OWaVokpkGa47Zmr3BogUAr6GXrBMBP5nVuvn65CGb54HRcMo7VuRmBVjNeIlm3SP6DBDJA/5wsLZkNvZdfJ/djrlimi2J+ED9gjg1cu5jlj1Rl3loHTf+2DwKMgvrZTIYycPxR7N7jcgIwmNNZv29gIQO/xRid+MZsi7wr/SzXLb5iWQBQeAmb9oMFndleaV5nDauKw64SQfY49jX4dSWQdObgSThECul1uHY3C4KOG0cHtYw83s/oi5Bon8g4RLVD+5B+kABLM=
  matrix:
    - CRATE=vhdl_parser
    - CRATE=vhdl_ls

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview

script:
  - cargo fmt --package $CRATE -- --check
  - cargo clippy --package $CRATE || true
  - cargo build --package $CRATE
  - cargo test --package $CRATE

before_deploy:
  - docker build -t kraigher/$CRATE:${TRAVIS_TAG:-latest} --build-arg RUST_VERSION=$TRAVIS_RUST_VERSION --build-arg CRATE=$CRATE .
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  # @TODO create tag after release
  - provider: script
    script:
      - cd $CRATE && cargo publish --token "${CRATES_IO_TOKEN}" || true
      - docker push kraigher/$CRATE:${TRAVIS_TAG:-latest}
    on:
      rust: stable
      branch: master
