sudo: required

services:
  - docker

language: rust

cache: cargo

rust:
  - stable
  - nightly

env:
  global:
    - secure: HCIhhVrX0hLJtnPGHzIaw60y4XDu9ZF6nHsDVqhWTukzM/J8jDoufVP70mm/dhTpIkrMHhs05/x9BRNqwHObuTW82SlyENs9714r9nljVD/qwy6I2gRbUPXY9p5CTeNeRrzkcaZa4nZ7lQ1R4GqlviH1bJfYqT0tO0wq+3LMvTdY2VCptfwUZZpfkQFw2F2uK4gFMnnJOiCHizbttdv7ZlSi75ngS+q+G0g6QAgUA4Xe5uo9KvNLJpNpQ4aQulyn4UuHBX+Nfqq1tq+UdxaLdXZOB7VWK/3BYnl9kSuFQMQoZ4DIGgYnURL39wsXmawkT7YIuhoHN4o3M7Z0Ay0lcTEq03ev9oMyxz4v/oQKpCBVUdbKL15IQsOrDynK3vh6MEqWyoyQfpQy+VhFlrY7wOrrkOhFXOsv2+lJzfodXVvlfKAwLuvASnbFV9l+z3+JA0L1IKWgiJXeIhsz6eSkkU/vReeNVIvwBN8Dk9HDrkeKJvFGkPZDNEsQhnrJ6jRHXq0sMSA6Y2RPYcup3uLzjrgdjB6NZvDjjNWrm+1J8Na28NzCy/O95eyn3fE5HVgfCSdDmwG7H4yQIUBAlflXLvXSEaK/8JGFXhsyG8pZEwQd70HlLWglxaIFOdpymr8oskymxFfGIz/ULKi9gcvuZrrec7JW1c/YEe2g9fWWsG4=
    - secure: YTs6ZBUtEBaraNu4PBlL4UYJ6YshuGrIgF4KHjNKaUGRE48V8XmCetuRZigx3zatQ0n+JAt77eYUhbYb0JCm4KII2G6YvOSbmg0RFH/FNlsGOqEToBLUdFyiHel3f+uphexEMUajFzpkN035l4Z6qFt2R/cmKQRaNmkrqa4WcomIOnXZugYgDsXsAephwGp+SUI+3barnvFMO82zK36lz5GxEsDGoMttqyiPLdRLjdESUEF2pajSYDnfJ4pXEGXCjCL4o/VPFpsOpgCbNjGMrZlXGenCocAooZLrnbqgaqRTw1cq05s5qApEd8OXZ0wgZqF8594GWUztCWl8DfPFBpNylcoSpUyNEShcA9KaMHjeyaXdBzXAaS3IITJ2Nkxofps7RasSxcTCYkD5klfCS8+jbxUWx0piXbBowlrrNpjEuSBHpkebjq9k1SBi7zMHM4vX2QKgvICEdegOcsBNr36LrtaC7Z+hcwFsd2y+JATCWXbve4aO9PFM4X4Ga/Sq7sxw/2yFwI4ljqW+HW11DJ3J36JXohwP41AJ2ffizFGLS9wmXfrw8SMJRTJMlGpMal6L9ymxnN1Ih3/lfGcxByM1vtNDmWKc6IOXQ+1HQBQRoQS5hfkP8xiKETTs8WJmVxKE4cNEOPP5WDzTiEANb4JnYoPTtjNNYKAPQX074Ak=
    - secure: D0XWwQ+iOd25TBlV3xrkS5RZrWQQfZgYPfMN+TlJYJjUn8VQKWVXKiHZHK3drsukiwgXv96xu6M5eOXt1NKucLqqgAwgWuVsjJ4zPP5tTsgMTqTrh4EToPuRuB8gAAr++91q4VYU+ntqOjRD5IT213ZVSTz4k7NpX96GH+HghvC9tdEOLi5kBJyOiKV/nROfjhEf9wPgXLqYrSzxQY8XV9AmTH1sW+i1krms12KgoAtuXVl8X0SYKqNFj1CZEWyZSLoZeeiL+zD7g24cC9YFdkniN+khyG8GY8h6qQaB6U/cRxS+cHcVlIqXNYRiad6BMMCiD/17qbXplyzXmuOkBKMnj0/0oHwW8saoIdEqZuwKx7GzoJUsLU9VUeMQFCPl47HOXh61BD+D2dUXJPBwemV8gwgSeunOUD7COO85LppndynOnwZMVb5KEF+EQWzhwxcD6QrdFU5xlVb8dxIxPT8gb5qzD1uXBkv/sqKfSVMlrtCJ31fTBStTd17nhF+HB04sQZe3U5wQj41wophXu4YqMIZ/xVNa1hoNMlGYtToB1rvc736jRAQwszPf52fvPmjrQiDtXKGfo8yxXehAr2DUhR8nAvR/jdSpylch0u3g0DY7V6/HGkJjQHlwtPxUgu6UKUsBT5LBxyJ7NvfGQW/PjWd0aX0e0ZNPZIw+G7U=
  matrix:
    - CRATE=vhdl_parser
    - CRATE=vhdl_ls

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview

script:
  - cargo fmt --package $CRATE -- --check
  - cargo clippy --package $CRATE || true
  - cargo build --package $CRATE
  - cargo test --package $CRATE

before_deploy:
  - docker build -t kraigher/$CRATE:${TRAVIS_TAG:-latest} --build-arg RUST_VERSION=$TRAVIS_RUST_VERSION --build-arg CRATE=$CRATE .
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  # @TODO create tag after release
  - provider: script
    script:
      - cd $CRATE && cargo publish --token "${CRATES_IO_TOKEN}" || true
      - docker push kraigher/$CRATE:${TRAVIS_TAG:-latest}
    on:
      rust: stable
      branch: master
