sudo: required

services:
  - docker

language: rust

cache: cargo

rust:
  - stable

env:
  matrix:
    - CRATE=vhdl_parser
    - CRATE=vhdl_ls

install:
  - rustup component add rustfmt

script:
  - cargo build --package $CRATE
  - cargo test --package $CRATE

deploy:
  - provider: script
    script: cd $CRATE && cargo publish --token "${CRATES_IO_TOKEN}" || true
    on:
      rust: stable
      branch: master
