# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018, Olof Kraigher olof.kraigher@gmail.com

[package]
name = "vhdl_ls"
version = "0.4.0"
authors = ["Olof Kraigher <olof.kraigher@gmail.com>"]
license = "MPL-2.0"
description = "VHDL Language Server"
repository = "https://github.com/kraigher/rust_hdl"

[dependencies]
vhdl_parser = { version = "^0", path = "../vhdl_parser"}
jsonrpc-core = "^9"
serde_json = "^1"
serde = "^1"
languageserver-types = "^0"
url = "^1"
fnv = "^1"

[dev-dependencies]
tempfile = "^3"