name: Docker

on:
  push:
    branches:
    - master
    tags:
    - '**'

jobs:
  publish:
    name: Publish
    strategy:
      matrix:
        crate:
        - vhdl_lang
        - vhdl_ls
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jerray/publish-docker-action@v1.0.3
      env:
        CRATE: ${{ matrix.crate }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kraigher/${{ matrix.crate }}
        auto_tag: true
        build_args: CRATE
